version: "3"
tasks:
  local-run:
    desc: "start service"
    cmds:
      - migrate -path ./migrations -database "postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable" up
      - go run cmd/server/main.go

  gen-mock:
    desc: "generating mocks for storage, service layers"
    cmds:
    - mockgen -source=internal/service/interface.go -destination=mocks/service/service_mock.go -package=mocks
    - mockgen -source=internal/storage/interface.go -destination=mocks/storage/storage_mock.go -package=mocks

  gen-migrations:
    desc: "generating migration files"
    cmd: migrate create -ext sql -dir ./migrations -seq qstn-bnk

  migrate-down:
    desc: "migrate down"
    cmd: migrate -path ./migrations -database "postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable" down

  test:
    desc: "testing"
    cmd: echo