// Code generated by MockGen. DO NOT EDIT.
// Source: internal/storage/interface.go
//
// Generated by this command:
//
//	mockgen -source=internal/storage/interface.go -destination=mocks/storage/storage_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	dto "okami-qstn-bnk/internal/models/dto"
	types "okami-qstn-bnk/internal/pkg/types"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockStorage is a mock of Storage interface.
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
	isgomock struct{}
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockStorage) Close(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockStorageMockRecorder) Close(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockStorage)(nil).Close), ctx)
}

// CreateQuestion mocks base method.
func (m *MockStorage) CreateQuestion(ctx context.Context, question *dto.Question, options *[]dto.Option) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateQuestion", ctx, question, options)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateQuestion indicates an expected call of CreateQuestion.
func (mr *MockStorageMockRecorder) CreateQuestion(ctx, question, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateQuestion", reflect.TypeOf((*MockStorage)(nil).CreateQuestion), ctx, question, options)
}

// CreateTemplate mocks base method.
func (m *MockStorage) CreateTemplate(ctx context.Context, t dto.TestTemplate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTemplate", ctx, t)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTemplate indicates an expected call of CreateTemplate.
func (mr *MockStorageMockRecorder) CreateTemplate(ctx, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTemplate", reflect.TypeOf((*MockStorage)(nil).CreateTemplate), ctx, t)
}

// DeleteQuestion mocks base method.
func (m *MockStorage) DeleteQuestion(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteQuestion", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteQuestion indicates an expected call of DeleteQuestion.
func (mr *MockStorageMockRecorder) DeleteQuestion(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteQuestion", reflect.TypeOf((*MockStorage)(nil).DeleteQuestion), ctx, id)
}

// DeleteTemplate mocks base method.
func (m *MockStorage) DeleteTemplate(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTemplate", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTemplate indicates an expected call of DeleteTemplate.
func (mr *MockStorageMockRecorder) DeleteTemplate(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTemplate", reflect.TypeOf((*MockStorage)(nil).DeleteTemplate), ctx, id)
}

// GetQuestionById mocks base method.
func (m *MockStorage) GetQuestionById(ctx context.Context, id uuid.UUID) (*dto.Question, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQuestionById", ctx, id)
	ret0, _ := ret[0].(*dto.Question)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQuestionById indicates an expected call of GetQuestionById.
func (mr *MockStorageMockRecorder) GetQuestionById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQuestionById", reflect.TypeOf((*MockStorage)(nil).GetQuestionById), ctx, id)
}

// GetQuestionsCollectionWithFilters mocks base method.
func (m *MockStorage) GetQuestionsCollectionWithFilters(ctx context.Context, role *types.ModelRole, topic *string, difficulty *int) ([]dto.Question, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQuestionsCollectionWithFilters", ctx, role, topic, difficulty)
	ret0, _ := ret[0].([]dto.Question)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQuestionsCollectionWithFilters indicates an expected call of GetQuestionsCollectionWithFilters.
func (mr *MockStorageMockRecorder) GetQuestionsCollectionWithFilters(ctx, role, topic, difficulty any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQuestionsCollectionWithFilters", reflect.TypeOf((*MockStorage)(nil).GetQuestionsCollectionWithFilters), ctx, role, topic, difficulty)
}

// GetRandomQuestion mocks base method.
func (m *MockStorage) GetRandomQuestion(ctx context.Context, templateId uuid.UUID) ([]dto.Question, []dto.Option, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRandomQuestion", ctx, templateId)
	ret0, _ := ret[0].([]dto.Question)
	ret1, _ := ret[1].([]dto.Option)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetRandomQuestion indicates an expected call of GetRandomQuestion.
func (mr *MockStorageMockRecorder) GetRandomQuestion(ctx, templateId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRandomQuestion", reflect.TypeOf((*MockStorage)(nil).GetRandomQuestion), ctx, templateId)
}

// GetTemplateById mocks base method.
func (m *MockStorage) GetTemplateById(ctx context.Context, id uuid.UUID) (*dto.TestTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTemplateById", ctx, id)
	ret0, _ := ret[0].(*dto.TestTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTemplateById indicates an expected call of GetTemplateById.
func (mr *MockStorageMockRecorder) GetTemplateById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTemplateById", reflect.TypeOf((*MockStorage)(nil).GetTemplateById), ctx, id)
}

// GetTemplatesCollectionWithFilters mocks base method.
func (m *MockStorage) GetTemplatesCollectionWithFilters(ctx context.Context, role *types.ModelRole, purpose *types.ModelPurpose) ([]dto.TestTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTemplatesCollectionWithFilters", ctx, role, purpose)
	ret0, _ := ret[0].([]dto.TestTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTemplatesCollectionWithFilters indicates an expected call of GetTemplatesCollectionWithFilters.
func (mr *MockStorageMockRecorder) GetTemplatesCollectionWithFilters(ctx, role, purpose any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTemplatesCollectionWithFilters", reflect.TypeOf((*MockStorage)(nil).GetTemplatesCollectionWithFilters), ctx, role, purpose)
}

// Ping mocks base method.
func (m *MockStorage) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockStorageMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockStorage)(nil).Ping), ctx)
}

// UpdateQuestion mocks base method.
func (m *MockStorage) UpdateQuestion(ctx context.Context, q dto.Question) (*dto.Question, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateQuestion", ctx, q)
	ret0, _ := ret[0].(*dto.Question)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateQuestion indicates an expected call of UpdateQuestion.
func (mr *MockStorageMockRecorder) UpdateQuestion(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateQuestion", reflect.TypeOf((*MockStorage)(nil).UpdateQuestion), ctx, q)
}

// UpdateTemplate mocks base method.
func (m *MockStorage) UpdateTemplate(ctx context.Context, t dto.TestTemplate) (*dto.TestTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTemplate", ctx, t)
	ret0, _ := ret[0].(*dto.TestTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTemplate indicates an expected call of UpdateTemplate.
func (mr *MockStorageMockRecorder) UpdateTemplate(ctx, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTemplate", reflect.TypeOf((*MockStorage)(nil).UpdateTemplate), ctx, t)
}
