// Code generated by MockGen. DO NOT EDIT.
// Source: internal/storage/interface.go
//
// Generated by this command:
//
//	mockgen -source=internal/storage/interface.go -destination=mocks/storage/storage_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	models "okami-qstn-bnk/internal/models/dto"
	types "okami-qstn-bnk/internal/pkg/types"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockStorage is a mock of Storage interface.
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
	isgomock struct{}
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// CreateQuestion mocks base method.
func (m *MockStorage) CreateQuestion(q models.Question) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CreateQuestion", q)
}

// CreateQuestion indicates an expected call of CreateQuestion.
func (mr *MockStorageMockRecorder) CreateQuestion(q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateQuestion", reflect.TypeOf((*MockStorage)(nil).CreateQuestion), q)
}

// CreateTemplate mocks base method.
func (m *MockStorage) CreateTemplate(t models.TestTemplate) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CreateTemplate", t)
}

// CreateTemplate indicates an expected call of CreateTemplate.
func (mr *MockStorageMockRecorder) CreateTemplate(t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTemplate", reflect.TypeOf((*MockStorage)(nil).CreateTemplate), t)
}

// DeleteQuestion mocks base method.
func (m *MockStorage) DeleteQuestion(id uuid.UUID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeleteQuestion", id)
}

// DeleteQuestion indicates an expected call of DeleteQuestion.
func (mr *MockStorageMockRecorder) DeleteQuestion(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteQuestion", reflect.TypeOf((*MockStorage)(nil).DeleteQuestion), id)
}

// DeleteTemplate mocks base method.
func (m *MockStorage) DeleteTemplate(id uuid.UUID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeleteTemplate", id)
}

// DeleteTemplate indicates an expected call of DeleteTemplate.
func (mr *MockStorageMockRecorder) DeleteTemplate(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTemplate", reflect.TypeOf((*MockStorage)(nil).DeleteTemplate), id)
}

// GetQuestionByID mocks base method.
func (m *MockStorage) GetQuestionByID(id uuid.UUID) models.Question {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQuestionByID", id)
	ret0, _ := ret[0].(models.Question)
	return ret0
}

// GetQuestionByID indicates an expected call of GetQuestionByID.
func (mr *MockStorageMockRecorder) GetQuestionByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQuestionByID", reflect.TypeOf((*MockStorage)(nil).GetQuestionByID), id)
}

// GetQuestionsCollectionWithFilters mocks base method.
func (m *MockStorage) GetQuestionsCollectionWithFilters(role *types.ModelRole, topic *string, difficulty *int) []models.Question {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQuestionsCollectionWithFilters", role, topic, difficulty)
	ret0, _ := ret[0].([]models.Question)
	return ret0
}

// GetQuestionsCollectionWithFilters indicates an expected call of GetQuestionsCollectionWithFilters.
func (mr *MockStorageMockRecorder) GetQuestionsCollectionWithFilters(role, topic, difficulty any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQuestionsCollectionWithFilters", reflect.TypeOf((*MockStorage)(nil).GetQuestionsCollectionWithFilters), role, topic, difficulty)
}

// GetTemplateById mocks base method.
func (m *MockStorage) GetTemplateById(id uuid.UUID) models.TestTemplate {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTemplateById", id)
	ret0, _ := ret[0].(models.TestTemplate)
	return ret0
}

// GetTemplateById indicates an expected call of GetTemplateById.
func (mr *MockStorageMockRecorder) GetTemplateById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTemplateById", reflect.TypeOf((*MockStorage)(nil).GetTemplateById), id)
}

// GetTemplatesCollectionWithFilters mocks base method.
func (m *MockStorage) GetTemplatesCollectionWithFilters(role *types.ModelRole, purpose *types.ModelPurpose) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetTemplatesCollectionWithFilters", role, purpose)
}

// GetTemplatesCollectionWithFilters indicates an expected call of GetTemplatesCollectionWithFilters.
func (mr *MockStorageMockRecorder) GetTemplatesCollectionWithFilters(role, purpose any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTemplatesCollectionWithFilters", reflect.TypeOf((*MockStorage)(nil).GetTemplatesCollectionWithFilters), role, purpose)
}

// UpdateQuestion mocks base method.
func (m *MockStorage) UpdateQuestion(q models.Question) models.Question {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateQuestion", q)
	ret0, _ := ret[0].(models.Question)
	return ret0
}

// UpdateQuestion indicates an expected call of UpdateQuestion.
func (mr *MockStorageMockRecorder) UpdateQuestion(q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateQuestion", reflect.TypeOf((*MockStorage)(nil).UpdateQuestion), q)
}

// UpdateTemplate mocks base method.
func (m *MockStorage) UpdateTemplate(t models.TestTemplate) models.TestTemplate {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTemplate", t)
	ret0, _ := ret[0].(models.TestTemplate)
	return ret0
}

// UpdateTemplate indicates an expected call of UpdateTemplate.
func (mr *MockStorageMockRecorder) UpdateTemplate(t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTemplate", reflect.TypeOf((*MockStorage)(nil).UpdateTemplate), t)
}
